services:
  db:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build: .\backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    build: .
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  pgdata: